Tutorial from: https://medium.com/emergent-future/simple-reinforcement-learning-with-tensorflow-part-0-q-learning-with-tables-and-neural-networks-d195264329d0

# Reinforced Learning tutorial

## Q-Table Learning

In [1]:
import gym
import numpy as np

In [148]:
import time

In [2]:
env = gym.make('FrozenLake-v0')

/home/matteo/repo/gym/gym/__init__.py:22: UserWarning: DEPRECATION WARNING: to improve load times, gym no longer automatically loads gym.spaces. Please run "import gym.spaces" to load gym.spaces on your own. This warning will turn into an error in a future version of gym.
  warnings.warn('DEPRECATION WARNING: to improve load times, gym no longer automatically loads gym.spaces. Please run "import gym.spaces" to load gym.spaces on your own. This warning will turn into an error in a future version of gym.')


In [141]:
env.render()

  (Down)
SFFF
FHFH
FFFH
HFFG


In [124]:
dirtoa = {
    'L' : 0,
    'D' : 1,
    'R' : 2,
    'U' : 3
}

In [154]:
env.reset()

for i in range(10):
    mya = env.step(dirtoa['U'])
    print("Myaction = {}".format(mya))
    env.render()
    time.sleep(1)

Myaction = (0, 0.0, False, {'prob': 0.3333333333333333})
  (Up)
SFFF
FHFH
FFFH
HFFG
Myaction = (0, 0.0, False, {'prob': 0.3333333333333333})
  (Up)
SFFF
FHFH
FFFH
HFFG
Myaction = (0, 0.0, False, {'prob': 0.3333333333333333})
  (Up)
SFFF
FHFH
FFFH
HFFG
Myaction = (0, 0.0, False, {'prob': 0.3333333333333333})
  (Up)
SFFF
FHFH
FFFH
HFFG
Myaction = (0, 0.0, False, {'prob': 0.3333333333333333})
  (Up)
SFFF
FHFH
FFFH
HFFG
Myaction = (0, 0.0, False, {'prob': 0.3333333333333333})
  (Up)
SFFF
FHFH
FFFH
HFFG
Myaction = (0, 0.0, False, {'prob': 0.3333333333333333})
  (Up)
SFFF
FHFH
FFFH
HFFG
Myaction = (1, 0.0, False, {'prob': 0.3333333333333333})
  (Up)
SFFF
FHFH
FFFH
HFFG
Myaction = (1, 0.0, False, {'prob': 0.3333333333333333})
  (Up)
SFFF
FHFH
FFFH
HFFG
Myaction = (0, 0.0, False, {'prob': 0.3333333333333333})
  (Up)
SFFF
FHFH
FFFH
HFFG


Implement Q-Table learning algorithm

In [142]:
# Initialize table with all zeros
# The table has NS x NA where NS is the number of possible states, NA the number of possible actions
# Element i, j represents the reward for the jth action taken at the ith states
# The number of states, in this specific example, is given by all possible positions in the lake, that is 4x4 = 16
Q = np.zeros((env.observation_space.n, env.action_space.n))

In [143]:
# Set learning parameters
lr = 0.8 # learning rate
y = 0.95 # discount factor for future possible rewards

# Number of FULL RUNS of the game
num_episodes = 4000

In [144]:
# Create list to contain total rewards and steps per episode
rList = list()

In [145]:
for i in range(num_episodes):
    
    # Initialization
    s = env.reset() # reset the game. s is the state (in this case, the initial one)
    rAll = 0
    d = False
    j = 0
    
    # The Q-Table learning algorithm
    while j < 99:
        j += 1
        
        # Choose an action by greedily (with noise) picking from Q table 
        a = np.argmax(Q[s, :] + np.random.randn(1, env.action_space.n)*(1.0/(i+1)))
        
        # Get new state and reward from environment
        s1, r, d, _ = env.step(a)
        
        # Update Q-table
        Q[s, a] = Q[s, a] + lr * (r + y*np.max(Q[s1, :]) - Q[s, a])
        
        rAll += r
        s = s1
        
        if d == True:
            break;
            
    rList.append(rAll)

In [146]:
print("Score over time: " +  str(sum(rList)/num_episodes))

Score over time: 0.456


In [147]:
print("Final Q-Table values:")
print(Q)

Final Q-Table values:
[[1.61130093e-01 4.50551482e-03 3.35418186e-03 3.45867371e-03]
 [9.86883287e-04 5.27369504e-04 1.85740921e-04 1.35085089e-01]
 [8.16692986e-04 9.12348597e-02 1.42453350e-03 2.41829185e-03]
 [5.83557003e-04 6.17233350e-04 8.65371811e-05 9.14263379e-02]
 [1.24256999e-01 6.23412153e-05 2.41307169e-05 1.91040159e-04]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [3.38561727e-05 7.59736614e-05 6.81520695e-06 1.78343990e-02]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [5.71562287e-04 8.72928591e-04 7.44105902e-04 1.65038957e-01]
 [1.17901955e-03 2.12356283e-01 3.03852124e-04 8.54078130e-05]
 [2.62278593e-02 1.00406515e-04 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 5.53308126e-04 3.19527889e-01 1.09849299e-03]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 1.23711456e-01]
 [0.00000000e+00 0.00000000e+00 0

In [21]:
import sys
import time

a = 0  
for x in range (0,3):  
    a = a + 1  
    b = ("Loading" + "." * a)
    # \r prints a carriage return first, so `b` is printed on top of the previous line.
    sys.stdout.write('\r'+b)
    time.sleep(0.5)
print (a)

Loading...3
